name = "joshuatree"
compatibility_date = "2025-01-01"
main = "worker.js"

[assets]
directory = "landing"
binding = "ASSETS"

[[kv_namespaces]]
binding = "WAITLIST"
id = "97c2fc5f19fc4210bec0337bb7ae045f"

[[routes]]
pattern = "joshuatree.heyitsmejosh.com"
custom_domain = true

[observability]
enabled = true
