#!/bin/sh
# Writes claude_cfg.h (gitignored, never committed): where the Console's `ask>` prompt finds the Claude relay and the
# token it sends. The relay's host and port come from CLAUDE_RELAY_HOST and CLAUDE_RELAY_PORT (default 10.0.2.2, which
# is the Mac as QEMU's user network sees it, and 8765, the relay's own default). The token comes from the file in
# CLAUDE_RELAY_TOKEN_FILE, default ~/.claude-relay-token, the same file docs/CLAUDE-APP.md has you make. No file, or a
# token the relay would refuse (16 to 63 printable characters), and the header holds an empty token: the build still
# links and the Console says `claude: no token`. The token goes in as bytes, never as a string or on a command line,
# and this script never prints it. The header is rewritten only when its contents change, so a build stays incremental.
set -eu
O=${1:-claude_cfg.h}
host=${CLAUDE_RELAY_HOST:-10.0.2.2}
port=${CLAUDE_RELAY_PORT:-8765}
file=${CLAUDE_RELAY_TOKEN_FILE:-$HOME/.claude-relay-token}
case "$host" in ''|*[!A-Za-z0-9.-]*) echo "claude_cfg: CLAUDE_RELAY_HOST must be an address or host name, using 10.0.2.2" >&2; host=10.0.2.2 ;; esac
case "$port" in ''|*[!0-9]*) port=0 ;; esac
if [ "$port" -lt 1 ] || [ "$port" -gt 65535 ]; then echo "claude_cfg: CLAUDE_RELAY_PORT must be 1 to 65535, using 8765" >&2; port=8765; fi
tok=
[ -r "$file" ] && tok=$(LC_ALL=C tr -d ' \t\r\n' < "$file")
n=${#tok}
if [ -n "$tok" ]; then
    [ -z "$(printf '%s' "$tok" | LC_ALL=C tr -d '!-~')" ] || n=0   # anything left is not printable ASCII
    if [ "$n" -lt 16 ] || [ "$n" -gt 63 ]; then echo "claude_cfg: the relay token must be 16 to 63 printable characters; building without one" >&2; tok=; n=0; fi
fi
umask 077
tmp=$O.tmp
{
    echo "/* Generated by claude_cfg.sh at build time. Never commit: it can hold the relay token. */"
    echo "#define CLAUDE_HOST \"$host\""
    echo "#define CLAUDE_PORT $port"
    echo "#define CLAUDE_TOKEN_LEN $n"
    printf 'static const unsigned char claude_token[] = {'
    [ -n "$tok" ] && printf '%s' "$tok" | od -An -v -tu1 | tr -s ' \n' '  ' | sed 's/^ *//; s/ *$//; s/ /, /g; s/$/, /'
    echo '0 };'
} > "$tmp"
if cmp -s "$tmp" "$O"; then rm -f "$tmp"; else mv "$tmp" "$O"; echo "claude_cfg: relay $host:$port, $([ "$n" -gt 0 ] && echo 'token set' || echo 'no token')" >&2; fi
