#!/bin/sh
# Writes wifi_cfg.h (gitignored, never committed): the network the Pi joins. Reads ssid= and psk= from
# WIFI_CONF, default ~/.config/joshuatree/wifi.conf (mode 600, never in the repo). No file or a bad passphrase (8 to 63
# characters) and the header holds an empty SSID: the build still links and the Pi only scans. Never prints the passphrase.
set -eu
O=${1:-wifi_cfg.h}
f=${WIFI_CONF:-$HOME/.config/joshuatree/wifi.conf}
ssid=; psk=
if [ -r "$f" ]; then
    ssid=$(sed -n 's/^ssid=//p' "$f" | head -1); psk=$(sed -n 's/^psk=//p' "$f" | head -1)
fi
if [ -n "$ssid" ] && { [ "${#ssid}" -gt 32 ] || [ "${#psk}" -lt 8 ] || [ "${#psk}" -gt 63 ]; }; then echo "wifi_cfg: ssid up to 32 and psk 8 to 63 characters; building without Wi-Fi join" >&2; ssid=; psk=; fi
bytes() { printf '%s' "$1" | od -An -v -tu1 | tr -s ' \n' ',' | sed 's/^,//; s/,$//'; }
umask 077
tmp=$O.tmp
{
    echo "/* Generated by wifi_cfg.sh at build time. Never commit: it holds the Wi-Fi passphrase. */"
    echo "#define WIFI_SSID_LEN ${#ssid}"
    echo "#define WIFI_PSK_LEN ${#psk}"
    echo "static const unsigned char wifi_ssid[] = {$(bytes "$ssid")${ssid:+,}0};"
    echo "static const unsigned char wifi_psk[] = {$(bytes "$psk")${psk:+,}0};"
} > "$tmp"
if cmp -s "$tmp" "$O" 2>/dev/null; then rm -f "$tmp"; else mv "$tmp" "$O"; fi
