#!/bin/sh
# Writes wifi_cfg.h (gitignored, never committed): the network the Pi joins. Reads ssid= and psk= from
# WIFI_CONF, default ~/.config/joshuatree/wifi.conf (mode 600, never in the repo). No file or a bad passphrase (8 to 63
# characters) and the header holds an empty SSID: the build still links and the Pi only scans. Never prints the passphrase or the key.
set -eu
O=${1:-wifi_cfg.h}
f=${WIFI_CONF:-$HOME/.config/joshuatree/wifi.conf}
ssid=; psk=
if [ "${JT_WIFI_DEV:-0}" = 1 ] && [ -r "$f" ]; then   # only a dev card (tools/flash-pi.sh) ever carries the network; a release build never does
    ssid=$(sed -n 's/^ssid=//p' "$f" | head -1); psk=$(sed -n 's/^psk=//p' "$f" | head -1)
fi
if [ -n "$ssid" ] && { [ "${#ssid}" -gt 32 ] || [ "${#psk}" -lt 8 ] || [ "${#psk}" -gt 63 ]; }; then echo "wifi_cfg: ssid up to 32 and psk 8 to 63 characters; building without Wi-Fi join" >&2; ssid=; psk=; fi
bytes() { printf '%s' "$1" | od -An -v -tu1 | tr -s ' \n' ',' | sed 's/^,//; s/,$//'; }
umask 077
# The PMK, PBKDF2-HMAC-SHA1(passphrase, SSID, 4096 rounds, 32 bytes), worked out here so the passphrase never reaches the kernel.
pmk=
[ -n "$ssid" ] && pmk=$(SSID="$ssid" PSK="$psk" python3 -c 'import os,hashlib; print(",".join(str(b) for b in hashlib.pbkdf2_hmac("sha1", os.environ["PSK"].encode(), os.environ["SSID"].encode(), 4096, 32)))')
tmp=$O.tmp
{
    echo "/* Generated by wifi_cfg.sh at build time. Never commit: it holds the network's key (the PMK, not the passphrase). */"
    echo "#define WIFI_SSID_LEN ${#ssid}"
    echo "static const unsigned char wifi_ssid[] = {$(bytes "$ssid")${ssid:+,}0};"
    echo "static const unsigned char wifi_pmk[32] = {${pmk:-0}};"
} > "$tmp"
if cmp -s "$tmp" "$O" 2>/dev/null; then rm -f "$tmp"; else mv "$tmp" "$O"; fi
