#!/usr/bin/env python3
"""Generates drivers/png_testdata.h: real PNG files built from the kernel's
own baked wallpaper (drivers/wallpaper.h), so `pngtest` can decode them
in-kernel and compare every pixel against wallpaper_rgb directly, no second
copy of the expected pixels needed.

The PNGs are written by hand here rather than through PIL's encoder on
purpose: the filter type of every scanline is chosen explicitly (cycling
None/Sub/Up/Average/Paeth) so all five reconstruction paths are provably
exercised, and the zlib level is chosen per image so the three DEFLATE
block kinds (stored, fixed Huffman, dynamic Huffman) each get real
coverage. The block kind is read back out of the produced stream and
asserted, not assumed.

Also emits an FNV-1a hash of each image's expected decoded bytes, computed
from PIL's own decode of the exact bytes embedded (the host-side reference
decoder), which pngtest prints for its own decode so tools/png-check.sh
can compare the two.
"""
import re, struct, sys, zlib, io
from PIL import Image

ROOT = __import__('os').path.dirname(__import__('os').path.dirname(__import__('os').path.abspath(__file__)))
hdr = open(f'{ROOT}/drivers/wallpaper.h').read()
W = int(re.search(r'#define WALLPAPER_W (\d+)', hdr).group(1))
H = int(re.search(r'#define WALLPAPER_H (\d+)', hdr).group(1))
body = hdr[hdr.index('{') + 1:hdr.rindex('}')]
wall = bytes(int(t) for t in body.replace('\n', '').split(',') if t.strip())
assert len(wall) == W * H * 3, (len(wall), W * H * 3)


def crop(x0, y0, w, h, alpha=False):
    rows = []
    for y in range(h):
        row = bytearray()
        for x in range(w):
            i = ((y0 + y) * W + (x0 + x)) * 3
            row += wall[i:i + 3]
            if alpha:
                row.append((x * 7 + y * 3) & 0xff)
        rows.append(bytes(row))
    return rows


def paeth(a, b, c):
    p = a + b - c
    pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
    if pa <= pb and pa <= pc:
        return a
    if pb <= pc:
        return b
    return c


def filter_row(ftype, row, prev, bpp):
    out = bytearray([ftype])
    for i, x in enumerate(row):
        a = row[i - bpp] if i >= bpp else 0
        b = prev[i] if prev else 0
        c = prev[i - bpp] if (prev and i >= bpp) else 0
        if ftype == 0:
            out.append(x)
        elif ftype == 1:
            out.append((x - a) & 0xff)
        elif ftype == 2:
            out.append((x - b) & 0xff)
        elif ftype == 3:
            out.append((x - ((a + b) >> 1)) & 0xff)
        else:
            out.append((x - paeth(a, b, c)) & 0xff)
    return bytes(out)


def chunk(tag, data):
    return struct.pack('>I', len(data)) + tag + data + struct.pack('>I', zlib.crc32(tag + data) & 0xffffffff)


def encode(rows, w, h, alpha, level, filters):
    bpp = 4 if alpha else 3
    raw = bytearray()
    prev = None
    for y, row in enumerate(rows):
        raw += filter_row(filters[y % len(filters)], row, prev, bpp)
        prev = row
    comp = zlib.compress(bytes(raw), level)
    ihdr = struct.pack('>IIBBBBB', w, h, 8, 6 if alpha else 2, 0, 0, 0)
    # split IDAT into several chunks so the multi-IDAT concatenation path is real
    idats = b''
    step = max(1, len(comp) // 3 + 1)
    for i in range(0, len(comp), step):
        idats += chunk(b'IDAT', comp[i:i + step])
    return b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', ihdr) + idats + chunk(b'IEND', b''), comp


def first_block_type(comp):
    # zlib header is 2 bytes; first DEFLATE block header: bit0 BFINAL, bits1-2 BTYPE
    return (comp[2] >> 1) & 3


def fnv1a(data):
    h = 0x811c9dc5
    for b in data:
        h ^= b
        h = (h * 0x01000193) & 0xffffffff
    return h


images = [
    # name, x0, y0, w, h, alpha, zlib level, filters, expected first BTYPE
    ('rgb_dyn',   320, 180, 320, 180, False, 9, [0, 1, 2, 3, 4], 2),
    ('rgba_stored', 40, 400, 64, 36, True, 0, [4, 3, 2, 1, 0], 0),
    ('rgb_fixed', 600, 20, 6, 5, False, 6, [1, 4, 2, 3, 0], 1),
]

out = ['#ifndef PNG_TESTDATA_H', '#define PNG_TESTDATA_H',
       '/* Generated by tools/gen_png_testdata.py from drivers/wallpaper.h.',
       '   Real PNG files (crops of the baked wallpaper), every scanline filter',
       '   type and every DEFLATE block kind covered. Do not hand-edit. */']
for name, x0, y0, w, h, alpha, level, filters, want_btype in images:
    rows = crop(x0, y0, w, h, alpha)
    png, comp = encode(rows, w, h, alpha, level, filters)
    bt = first_block_type(comp)
    assert bt == want_btype, (name, bt, want_btype)
    # host-side reference decode of the exact bytes being embedded
    im = Image.open(io.BytesIO(png))
    assert im.size == (w, h) and im.mode == ('RGBA' if alpha else 'RGB'), (im.size, im.mode)
    ref = im.tobytes()
    assert ref == b''.join(rows), name
    hsh = fnv1a(ref)
    print(f'{name}: {w}x{h} {"RGBA" if alpha else "RGB"} level={level} btype={bt} png={len(png)}B fnv1a=0x{hsh:08x}')
    up = name.upper()
    out.append(f'#define PNGT_{up}_X0 {x0}')
    out.append(f'#define PNGT_{up}_Y0 {y0}')
    out.append(f'#define PNGT_{up}_W {w}')
    out.append(f'#define PNGT_{up}_H {h}')
    out.append(f'#define PNGT_{up}_CH {4 if alpha else 3}')
    out.append(f'#define PNGT_{up}_FNV 0x{hsh:08x}u')
    out.append(f'static const unsigned char pngt_{name}[{len(png)}] = {{')
    for i in range(0, len(png), 24):
        out.append(','.join(str(b) for b in png[i:i + 24]) + ',')
    out.append('};')
out.append('#endif')
open(f'{ROOT}/drivers/png_testdata.h', 'w').write('\n'.join(out) + '\n')
print('wrote drivers/png_testdata.h')
