/* Generated by tools/gen/gen_hamurabi_story.py from art/hamurabi/story.json. Do not edit by hand. */
#ifndef HAMURABI_STORY_H
#define HAMURABI_STORY_H

typedef struct {
    const char *label, *then;
    int grain, acres, acres_pct, people, yield_bonus, guard, peek;
    int has_gamble;
    unsigned long long gamble_thr; /* ceil(chance * 2^53) */
    int gamble_acres;
    const char *gamble_then;
} hamurabi_choice;

typedef struct {
    const char *id, *title, *text;
    int needs_grain, needs_acres, needs_people;
    hamurabi_choice choice[2];
} hamurabi_omen;

typedef struct { int year; const char *title, *text; } hamurabi_interlude;

static const char hamurabi_intro_title[] = "You are king";
static const char hamurabi_intro_text[] = "The old king is dead. Now you are king. You have 10 years to show what kind of king you are.";

#define HAMURABI_INTERLUDES 2
static const hamurabi_interlude hamurabi_interludes[HAMURABI_INTERLUDES] = {
    { 5, "Halfway", "Half your time is gone. People are starting to talk about how you rule." },
    { 10, "The last year", "This is your last year. Make it count." },
};

/* The ending line for each grade, indexed like hamurabi_grade(): F, C, B, A+. */
static const char *const hamurabi_epilogues[4] = {
    "The people have had enough. They never want to hear your name again.",
    "People remember being hungry. Many are glad you are done.",
    "You did okay. A few people went hungry who did not need to.",
    "You were a great king. Almost nobody went hungry, and there is plenty of land for everyone.",
};

/* A tip for years 1 to 4, indexed by year - 1. */
static const char *const hamurabi_hints[4] = {
    "Each person eats 20 bushels a year. Feed everyone and more people will come.",
    "One person can farm 10 acres. Each acre needs 1 bushel of seed.",
    "Land costs less in some years. Buy when it is cheap. Sell when it costs a lot.",
    "Rats, sickness and bad harvests can come any time. Save some grain.",
};

#define HAMURABI_OMENS 10
static const hamurabi_omen hamurabi_omens[HAMURABI_OMENS] = {
    { "caravan", "Traders", "Traders want to buy land by the river. They will pay a lot.",
      0, 400, 0,
      { { "Sell 40 acres", "The traders pay you 1,200 bushels.", 1200, -40, 0, 0, 0, 0, 0, 0, 0ULL, 0, "" },
        { "Say no", "The traders move on.", 0, 0, 0, 0, 0, 0, 0, 0, 0ULL, 0, "" } } },
    { "temple", "The priests", "The priests want grain to build a new altar. Your people are watching.",
      400, 0, 0,
      { { "Give 200 bushels", "People hear you are kind. 8 new people move in.", -200, 0, 0, 8, 0, 0, 0, 0, 0ULL, 0, "" },
        { "Say no", "The priests are angry. 5 people leave with them.", 0, 0, 0, -5, 0, 0, 0, 0, 0ULL, 0, "" } } },
    { "refugees", "At the gate", "A flood wrecked a town up the river. Families are waiting at your gate.",
      0, 0, 0,
      { { "Let them in", "15 people join your city. They can work, but they need to eat.", 0, 0, 0, 15, 0, 0, 0, 0, 0ULL, 0, "" },
        { "Send them away", "They walk on. The gate closes.", 0, 0, 0, 0, 0, 0, 0, 0, 0ULL, 0, "" } } },
    { "cats", "Cats for sale", "A trader is selling cats. Cats hunt rats.",
      300, 0, 0,
      { { "Buy cats for 150 bushels", "The cats guard the grain. No rats this year.", -150, 0, 0, 0, 0, 1, 0, 0, 0ULL, 0, "" },
        { "Keep your grain", "The trader leaves with his cats.", 0, 0, 0, 0, 0, 0, 0, 0, 0ULL, 0, "" } } },
    { "flood", "The river is rising", "The river is rising. You can pay to fix the walls that hold it back.",
      300, 0, 0,
      { { "Fix the walls for 200 bushels", "The walls hold. Your fields stay dry.", -200, 0, 0, 0, 0, 0, 0, 0, 0ULL, 0, "" },
        { "Do nothing", "The river floods your low fields. You lose some land.", 0, 0, -8, 0, 0, 0, 0, 0, 0ULL, 0, "" } } },
    { "tribute", "A greedy king", "A king nearby wants you to pay him. He has an army.",
      400, 0, 0,
      { { "Pay 300 bushels", "His men take the grain and go.", -300, 0, 0, 0, 0, 0, 0, 0, 0ULL, 0, "" },
        { "Say no", "Nothing happens. This time.", 0, 0, 0, 0, 0, 0, 0, 1, 4503599627370496ULL, -100, "His army takes 100 acres from you." } } },
    { "festival", "A party", "Your people want a big party after the harvest.",
      500, 0, 0,
      { { "Throw a party for 300 bushels", "The party is so good that 10 visitors stay for good.", -300, 0, 0, 10, 0, 0, 0, 0, 0ULL, 0, "" },
        { "Not this year", "Everyone goes back to work.", 0, 0, 0, 0, 0, 0, 0, 0, 0ULL, 0, "" } } },
    { "barley", "Better seed", "A farmer is selling better seed. He says it grows more grain.",
      400, 0, 0,
      { { "Buy seed for 250 bushels", "You plant the new seed. Each acre gives 1 more bushel this year.", -250, 0, 0, 0, 1, 0, 0, 0, 0ULL, 0, "" },
        { "Keep the old seed", "The farmer leaves.", 0, 0, 0, 0, 0, 0, 0, 0, 0ULL, 0, "" } } },
    { "stars", "The star reader", "A woman who reads the stars says she knows how the harvest will go. She wants to be paid.",
      200, 0, 0,
      { { "Pay 100 bushels", "She looks at the sky.", -100, 0, 0, 0, 0, 0, 1, 0, 0ULL, 0, "" },
        { "Say no", "She packs up her maps.", 0, 0, 0, 0, 0, 0, 0, 0, 0ULL, 0, "" } } },
    { "steward", "A thief", "Your helper was caught stealing grain. He says sorry and promises to work harder.",
      0, 0, 0,
      { { "Kick him out", "He leaves at night. You find 150 bushels in his house.", 150, 0, 0, 0, 0, 0, 0, 0, 0ULL, 0, "" },
        { "Forgive him", "He works day and night. You gain 30 acres of new fields.", 0, 30, 0, 0, 0, 0, 0, 0, 0ULL, 0, "" } } },
};

#endif
