/* Generated by tools/gen/gen_hamurabi_story.py. Do not edit by hand. */
#ifndef HAMURABI_STORY_H
#define HAMURABI_STORY_H

static const char hamurabi_intro_title[] = "You are king";
static const char hamurabi_intro_text[] = "The old king is dead. Now you are king. You have 10 years to show what kind of king you are.";

static const char hamurabi_interlude_5_title[] = "Halfway";
static const char hamurabi_interlude_5_text[] = "Half your time is gone. People are starting to talk about how you rule.";
static const char hamurabi_interlude_10_title[] = "The last year";
static const char hamurabi_interlude_10_text[] = "This is your last year. Make it count.";

static const char hamurabi_omen_ids[] = "caravan" "temple" "refugees" "cats" "flood" "tribute" "festival" "barley" "stars" "steward";
#endif
